### ISSUE TITLE
check-dns-serial bug report

### ISSUE THREAD

**Issue by craigbowden76** [bowdoincollege/noc-commit-hooks#4]
The serial was 2021091300; when I went to commit and I got the error:

/Users/cbowden/.cache/pre-commit/repom0j5xgwk/hooks/check-dns-serial.sh: line 73: "10#00" + 1: syntax error: operand expected (error token is ""10#00" + 1")

**Comment by oasys** [comment]
What version of `bash` are you using?  (run `echo $BASH_VERSION`)

**Comment by craigbowden76** [comment]
C02ZF3CRLVDM:~ cbowden$ echo $BASH_VERSION
3.2.57(1)-release

**Comment by oasys** [comment]
That's a bit ancient.   I suspect you're running the included macOS bash.

```bash
sapphire:~$ /bin/bash
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
sapphire:~$ echo $BASH_VERSION
3.2.57(1)-release
sapphire:~$ echo $(("10#0" + 1))
bash: "10#0" + 1: syntax error: operand expected (error token is ""10#0" + 1")
```
As a workaround, try installing a more recent version, `brew install bash`.

```bash
sapphire:~$ echo $BASH_VERSION
5.1.8(1)-release
sapphire:~$ echo $(("10#0" + 1))
1
```

Longer-term, I think this is just a problem with how the older bash interprets the quoting.  (`$((10#0 + 1)` works without error.)   Leave this issue open and I'll work up a fix.
